title: 3D Vision arXiv Daily
description: Daily radar for 3D vision papers with curated topics and code links.
show_downloads: true

repo_url: https://github.com/yolo079/Vision-arxiv-daily
pages_url: https://yolo079.github.io/Vision-arxiv-daily/

github:
  zip_url: https://github.com/yolo079/cv-arxiv-daily
  another_url: https://github.com/yolo079/cv-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
